version: '3.8'
services:
  web:
    build: .
    ports:
      - "3010:3010"
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 30For30!
    volumes:
      - mydbdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  mydbdata:
